"""Regenerate Vx packed batch exports after the decoder/matvec section.

Independent token lanes preserve each dot's ordered F32 reduction. Transposed
activation storage makes adjacent token lanes contiguous for LLVM SLP. The
quantized scalar weight is decoded once and reused across up to 64 tokens.
"""
from pathlib import Path
from kernels.packed import LAYOUTS

MARKER = '// BEGIN GENERATED PACKED BATCH EXPORTS'


def generate(max_tile=64, layout="tile"):
    if layout not in ("tile", "column") or (layout == "tile" and max_tile != 64):
        raise ValueError("tile layout requires max_tile=64; column supports candidate tile sizes")
    if max_tile not in (8, 16, 32, 64):
        raise ValueError("max tile must be 8, 16, 32 or 64")
    lines = [MARKER,
        '// Generated by python -m kernels.generate_packed_batch; do not hand edit.',
        '// x packs [cols,tile] blocks (64/32/16/8/4/2/1); output is [batch,rows].' if layout == 'tile' else '// x is transposed [cols,batch]; output is [batch,rows].',
        '// No horizontal reduction, reassociation, FMA, or activation quantization.']
    for block, size, suffix in LAYOUTS.values():
        lines += [f'fn glm_vx_packed_batch_{"v2_" if layout == "tile" else ""}{suffix}(out: *mut f32, w: *const u8, x: *const f32, half: *const f32, table: *const u8, rows: i32, cols: i32, batch: i32) -> i32 {{',
                  f'  if rows < 0 || cols <= 0 || cols % {block} != 0 || batch < 0 || batch > 64 {{ return -1; }}',
                  f'  let blocks: i32 = cols / {block};',
                  '  unsafe {', '    let mut token: i32 = 0;']
        for tile in (2**i for i in range(max_tile.bit_length()-1, -1, -1)):
            lines += [f'    let count{tile}: i32 = (batch - token) / {tile};', f'    for tile_index in 0..count{tile} {{', '      for r in 0..rows {']
            lines += [f'        let mut s{i}: f32 = 0.0;' for i in range(tile)]
            lines += ['        for block in 0..blocks {',
                      f'          let b: i32 = (r * blocks + block) * {size};',
                      f'          for j in 0..{block} {{',
                      f'            let v: f32 = packed_weight_{suffix}(w, b, j, half, table);',
                      f'            let p: i32 = token * cols + (block * {block} + j) * {tile};' if layout == 'tile' else f'            let p: i32 = (block * {block} + j) * batch + token;']
            lines += [f'            s{i} = s{i} + v * x[p + {i}];' for i in range(tile)]
            lines += ['          }', '        }']
            lines += [f'        out[(token + {i}) * rows + r] = s{i};' for i in range(tile)]
            lines += ['      }', f'      token = token + {tile};', '    }']
        lines += ['  }', '  return 0;', '}', '']
    return '\n'.join(lines).rstrip()


if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--max-tile', type=int, default=64)
    parser.add_argument('--layout', choices=('tile', 'column'), default='tile')
    parser.add_argument('--output', type=Path)
    args = parser.parse_args()
    path = Path(__file__).with_name('packed.vx')
    prefix = path.read_text().split(MARKER)[0].rstrip()
    output = args.output or path
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(prefix + '\n\n' + generate(args.max_tile, args.layout) + '\n')
